// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
	"blog/internal/model/entity"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/util/gconv"
)

// adminDao is the data access object for the table admin.
// You can define custom methods on it to extend its functionality as needed.
type adminDao struct {
	*internal.AdminDao
}

var (
	// Admin is a globally accessible object for table admin operations.
	Admin = adminDao{internal.NewAdminDao()}
)

// Add your custom methods and functionality below.

// GetAdmin 根据username获取管理员
func (a adminDao) GetAdmin(username string) (admin *entity.Admin) {
	data, err := g.Model(Admin.Table()).Where("username", username).One()
	if err != nil {
		return nil
	}
	_ = gconv.Struct(data, &admin)
	return
}
