// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// articleDao is the data access object for the table article.
// You can define custom methods on it to extend its functionality as needed.
type articleDao struct {
	*internal.ArticleDao
}

var (
	// Article is a globally accessible object for table article operations.
	Article = articleDao{internal.NewArticleDao()}
)

// Add your custom methods and functionality below.
