// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// articleGrpDao is the data access object for the table article_grp.
// You can define custom methods on it to extend its functionality as needed.
type articleGrpDao struct {
	*internal.ArticleGrpDao
}

var (
	// ArticleGrp is a globally accessible object for table article_grp operations.
	ArticleGrp = articleGrpDao{internal.NewArticleGrpDao()}
)

// Add your custom methods and functionality below.
