// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// linkDao is the data access object for the table link.
// You can define custom methods on it to extend its functionality as needed.
type linkDao struct {
	*internal.LinkDao
}

var (
	// Link is a globally accessible object for table link operations.
	Link = linkDao{internal.NewLinkDao()}
)

// Add your custom methods and functionality below.
