// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// replyDao is the data access object for the table reply.
// You can define custom methods on it to extend its functionality as needed.
type replyDao struct {
	*internal.ReplyDao
}

var (
	// Reply is a globally accessible object for table reply operations.
	Reply = replyDao{internal.NewReplyDao()}
)

// Add your custom methods and functionality below.
