// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// sentenceDao is the data access object for the table sentence.
// You can define custom methods on it to extend its functionality as needed.
type sentenceDao struct {
	*internal.SentenceDao
}

var (
	// Sentence is a globally accessible object for table sentence operations.
	Sentence = sentenceDao{internal.NewSentenceDao()}
)

// Add your custom methods and functionality below.
