// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// tagDao is the data access object for the table tag.
// You can define custom methods on it to extend its functionality as needed.
type tagDao struct {
	*internal.TagDao
}

var (
	// Tag is a globally accessible object for table tag operations.
	Tag = tagDao{internal.NewTagDao()}
)

// Add your custom methods and functionality below.
