// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"blog/internal/dao/internal"
)

// tagGrpDao is the data access object for the table tag_grp.
// You can define custom methods on it to extend its functionality as needed.
type tagGrpDao struct {
	*internal.TagGrpDao
}

var (
	// TagGrp is a globally accessible object for table tag_grp operations.
	TagGrp = tagGrpDao{internal.NewTagGrpDao()}
)

// Add your custom methods and functionality below.
