// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package article_grp

import (
	"blog/api/article_grp"
)

type ControllerApp struct{}

func NewApp() article_grp.IArticleGrpApp {
	return &ControllerApp{}
}

type ControllerV1 struct{}

func NewV1() article_grp.IArticleGrpV1 {
	return &ControllerV1{}
}
